version: "3.10"
   
services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn Site.wsgi:application --bind 0.0.0.0:8000
    container_name: 'gunicorn web'
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: 'database'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    container_name: 'nginx'
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq:/data/var/lib/rabbitmq/
        - rabbitmq:/log/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

volumes:

  postgres_data:
  static_volume:
  media_volume:
  rabbitmq:

networks:
  rabbitmq_go_net:
    driver: bridge