version: "3.10"
   
services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: >
      sh -c "python manage.py createcachetable
             python manage.py migrate --noinput
             python manage.py collectstatic --no-input --clear
             gunicorn Site.wsgi:application --bind 0.0.0.0:8000"
    container_name: 'gunicorn_web'
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: 'database'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    container_name: 'nginx'
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

  celery:
    build: ./
    command: celery -A Site worker --beat --loglevel=info
    container_name: 'celery'
    depends_on:
      - web
      - redis

  redis:
    image: redis:7-alpine
    container_name: 'redis'
    restart: always
    expose:
      - '6379'
    ports:
      - '6379:6379'

volumes:

  postgres_data:
  static_volume:
  media_volume:
  celery: